all:
		gcc mkfifo.c -o mkfifo
		gcc fifo_sender.c -o fifo_sender
		gcc fifo_reciver.c -o fifo_reciver
		gcc socket_sender.c -o socket_sender
		gcc socket_reciver.c -o socket_reciver
		gcc share_sender.c -o share_sender
		gcc shared_recived.c -o shared_recived
clean:
		-rm mkfifo 
		-rm fifo_sender
		-rm fifo_reciver
		-rm socket_sender
		-rm socket_reciver
		-rm share_sender
		-rm shared_recived